import os
from datetime import date

import result as result

import data
from data import *
from file import *
from val import *
from tkinter import Tk
from tkinter.filedialog import askopenfilename
from PyQt5.QtWidgets import QMainWindow, QMessageBox, QAction, QStyledItemDelegate
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import doctor
import patient

class ReadOnlyDelegate(QStyledItemDelegate):
    def createEditor(self, parent, option, index):
        return

class Ui_MainWindow(QMainWindow):
    def __init__(self, parent=None):
        super(Ui_MainWindow, self).__init__(parent)
        with open('config/config.json') as f:
            config = json.load(f)
        self.cnx = data.connect_sql(config)
        data.connect_database(self.cnx, config['database_name'])
        self.cursor = self.cnx.cursor()

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(945, 725)
        icon = QtGui.QIcon()
        self.setWindowIcon(QtGui.QIcon("./icon/logo.png"))
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        delegate = ReadOnlyDelegate(self)
        self.tableWidget.setItemDelegateForColumn(0, delegate)
        self.tableWidget.setItemDelegateForColumn(1, delegate)
        self.tableWidget.setItemDelegateForColumn(2, delegate)
        self.tableWidget.setItemDelegateForColumn(3, delegate)
        self.tableWidget.setItemDelegateForColumn(4, delegate)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 801, 271))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(830, 80, 75, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(830, 130, 75, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, -10, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 340, 801, 321))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 721, 241))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 180, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(110, 39, 561, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit.setGeometry(QtCore.QRect(520, 100, 151, 31))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(110, 100, 161, 31))
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(20, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(440, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(30, 70, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(30, 110, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(30, 150, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 30, 571, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 70, 571, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 110, 571, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(130, 150, 571, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(350, 250, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, -30, 801, 331))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 30, 691, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 40, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(300, 90, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(90, 39, 581, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(30, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setGeometry(QtCore.QRect(30, 70, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(30, 110, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(30, 150, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(130, 30, 571, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_9.setGeometry(QtCore.QRect(130, 110, 571, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_10.setGeometry(QtCore.QRect(130, 150, 571, 31))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_6.setGeometry(QtCore.QRect(350, 210, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.dateTimeEdit_3 = QtWidgets.QDateTimeEdit(self.tab_4)
        self.dateTimeEdit_3.setGeometry(QtCore.QRect(130, 71, 194, 31))
        self.dateTimeEdit_3.setObjectName("dateTimeEdit_3")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 945, 21))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        self.init_data(data.get_all_records(self.cnx.cursor(), 'schedule'))
        self.pushButton.clicked.connect(self.import_button_click)
        self.pushButton_2.clicked.connect(self.export_button_click)
        self.pushButton_3.clicked.connect(self.search_schedule)
        self.pushButton_6.clicked.connect(self.add_schedule)


        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(1)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Schedule Manage"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Doctor"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Patient"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Result"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Edit"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Delete"))
        self.pushButton.setText(_translate("MainWindow", "Import"))
        self.pushButton_2.setText(_translate("MainWindow", "Export"))
        self.label.setText(_translate("MainWindow", "Schedules"))
        self.groupBox.setTitle(_translate("MainWindow", "Search Schedule"))
        self.label_2.setText(_translate("MainWindow", "Name:"))
        self.pushButton_3.setText(_translate("MainWindow", "Search Schedule"))
        self.label_13.setText(_translate("MainWindow", "Date from:"))
        self.label_14.setText(_translate("MainWindow", "Date to:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Search"))
        self.label_3.setText(_translate("MainWindow", "Name:"))
        self.label_4.setText(_translate("MainWindow", "Phone:"))
        self.label_5.setText(_translate("MainWindow", "Email:"))
        self.label_6.setText(_translate("MainWindow", "Address:"))
        self.pushButton_4.setText(_translate("MainWindow", "Add"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Search Doctor"))
        self.label_7.setText(_translate("MainWindow", "Name:"))
        self.pushButton_5.setText(_translate("MainWindow", "Search Doctor"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Search"))
        self.label_8.setText(_translate("MainWindow", "Name:"))
        self.label_9.setText(_translate("MainWindow", "Date:"))
        self.label_10.setText(_translate("MainWindow", "Doctor ID:"))
        self.label_11.setText(_translate("MainWindow", "Patient ID:"))
        self.pushButton_6.setText(_translate("MainWindow", "Add"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Add new"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Add new"))

    def init_data(self,results):
        for i in range(0, len(results)):
            self.tableWidget.insertRow(i)
            self.tableWidget.setItem(i, 0, QtWidgets.QTableWidgetItem(str(results[i][0])))
            self.tableWidget.setItem(i, 1, QtWidgets.QTableWidgetItem(str(results[i][1])))
            self.tableWidget.setItem(i, 2, QtWidgets.QTableWidgetItem(str(results[i][2])))
            self.tableWidget.setItem(i, 3, QtWidgets.QTableWidgetItem(str(results[i][3])))
            self.tableWidget.setItem(i, 4, QtWidgets.QTableWidgetItem(str(results[i][4])))
            self.tableWidget.setItem(i, 5, QtWidgets.QTableWidgetItem(str(results[i][5])))


            self.detail_btn = QtWidgets.QPushButton(self)
            self.detail_btn.clicked.connect(self.edit_btn_click)
            self.detail_btn.setText("Edit")
            self.tableWidget.setCellWidget(i, 6, self.detail_btn)
            self.detail_btn = QtWidgets.QPushButton(self)
            self.detail_btn.clicked.connect(self.delete_btn_click)
            self.detail_btn.setText("Delete")
            self.tableWidget.setCellWidget(i, 7, self.detail_btn)


    def search_schedule(self):
        name_input = self.lineEdit.text()
        date_from = self.dateTimeEdit_2.dateTime().toPyDateTime()
        date_to = self.dateTimeEdit.dateTime().toPyDateTime()

        result = data.schedule_exist(self.cursor, name_input, date_from, date_to)
        self.tableWidget.clearContents()
        self.tableWidget.setRowCount(0)
        if len(result) != 0:
            self.init_data(result)
        else:
            QMessageBox.information(self, 'Message', 'Nothing found!', QMessageBox.Close)

    def edit_btn_click(self):
        button = QtWidgets.qApp.focusWidget()
        index = self.tableWidget.indexAt(button.pos())
        table_model = self.tableWidget.model()
        id_index = table_model.index(index.row(), 0)
        id = table_model.data(id_index)
        name_index = table_model.index(index.row(), 1)
        name = table_model.data(name_index)
        date_index = table_model.index(index.row(), 2)
        date = table_model.data(date_index)
        doctor_index = table_model.index(index.row(), 3)
        doctor = table_model.data(doctor_index)
        patient_index = table_model.index(index.row(), 4)
        patient = table_model.data(patient_index)
        result_index = table_model.index(index.row(), 5)
        result = table_model.data(result_index)
        print(id, name, date, doctor, patient, result)
        labels = ('name', 'date', 'doctor', 'patient', 'result')
        values = (name, date, doctor, patient, result)
        update_by_id(self.cnx, 'schedule', labels, values, id)


    def add_schedule(self):
        name = self.lineEdit_7.text()
        datetime = self.dateTimeEdit_3.dateTime().toPyDateTime()
        doctor = self.lineEdit_9.text()
        patient = self.lineEdit_10.text()
        labels = ('name', 'date', 'doctor_id', 'patient_id')
        values = (name, datetime, doctor, patient)
        print(values)
        if insert_table(self.cnx, 'schedule', labels, values):
            result = get_last_n_rows(self.cnx.cursor(), 'schedule', 1)
            if result:
                self.init_data(result)

    def delete_btn_click(self):
        button = QtWidgets.qApp.focusWidget()
        index = self.tableWidget.indexAt(button.pos())
        table_model = self.tableWidget.model()
        id_index = table_model.index(index.row(), 0)
        id = table_model.data(id_index)
        print(id)
        name_index = table_model.index(index.row(), 1)
        name = table_model.data(name_index)
        ques = QMessageBox.question(self, 'System', f'Are you sure you want to delete schedule: {name}?',
                                    QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
        if ques == QMessageBox.Yes:
            if delete_by_id(self.cnx, 'hospital', id):
                QMessageBox.about(self, "System", f"Successfully delete the schedule: {name}")
                self.tableWidget.clearContents()
                self.tableWidget.setRowCount(0)
                self.init_data(data.get_all_records(self.cnx.cursor(), 'schedule'))
            else:
                QMessageBox.about(self, "System", "Delete failed, try again")


    def import_button_click(self):
        try:
            Tk().withdraw()
            fname = askopenfilename()
            if fname == '':
                return False

            tail = re.findall("[.]{1}\w+$", fname)[0]
            if not tail == '.xlsx':
                QMessageBox.information(self, 'Error', 'Must be an excel file', QMessageBox.Close)
                return False

            df = load_from_file(fname).fillna('')
            count = 0
            attributes = ('name', 'date', 'doctor_id', 'patient_id')
            for i in range(len(df)):
                name = str(df.iloc[i]['name'])
                date = str(df.iloc[i]['date'])
                doctor = str(df.iloc[i]['doctor'])
                patient = str(df.iloc[i]['patient'])
                values = [name, date, doctor, patient]
                count += 1
                insert_table(self.cnx, 'schedule', attributes, values)

            records = get_last_n_rows(self.cnx.cursor(), 'schedule', count)
            self.init_data(data.get_all_records(self.cnx.cursor(), 'schedule'))
            QMessageBox.information(self, 'Success', 'Import successfully', QMessageBox.Close)
        except:
            print('Error')


    def export_button_click(self):
        try:
            records = get_all_records(self.cnx.cursor(), 'schedule')
            attributes = ('id', 'name', 'date', 'doctor_id', 'patient_id')
            save_to_file('schedule', records, attributes)
            print(1)
            return True
        except:
            return False

if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_MainWindow()
    ui.setupUi()
    ui.show()
    sys.exit(app.exec_())
